// src/app/layout.js
import localFont from 'next/font/local';
import "./globals.css";
import AnimatedLayout from "../components/AnimatedLayout";

const monument = localFont({
  src: [
    { path: '../../public/fonts/ABCMonumentGrotesk-Medium-Trial.woff2', weight: '500', style: 'normal' },
  ],
  variable: '--font-monument',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning prevents React from complaining about minor attribute differences
          injected by browser extensions (for example Grammarly) before hydration */}
      <body suppressHydrationWarning className={`${monument.variable}`}>
        <AnimatedLayout>{children}</AnimatedLayout>
      </body>
    </html>
  );
}