// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnimatedLayout from "../components/AnimatedLayout"; // we'll create this next

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning prevents React from complaining about minor attribute differences
          injected by browser extensions (for example Grammarly) before hydration */}
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable}`}>
        <AnimatedLayout>{children}</AnimatedLayout>
      </body>
    </html>
  );
}